import os
import re

from openpyxl import Workbook


def find_all_case(path):
    def txt_or_cs(case):
        if case.endswith('.txt'):  # 找到以.txt结尾的文件
            txt_path_list.append(case)
        elif case.endswith('.cs') or case.endswith('.json') or case.endswith('.xml'):
            cs_path_list.append(case)

    dir_files = os.listdir(path)  # 找到当前文件夹下所有文件
    for case in dir_files:
        case_path = os.path.join(path, case)  # 拼接成绝对路径
        if os.path.isfile(case_path):  # 如果是文件,得到文件路径
            txt_or_cs(case_path)
        elif os.path.isdir(case_path):  # 如果是子文件夹,继续递归
            find_all_case(case_path)


def unique_PD():
    for x in patient_names:
        if x in dicom_names:
            duplicated_PD.append(x)
    # duplicated_PD = ("4DLung",
    #                  "BigAlFFS",
    #                  "BigAlHFS",
    #                  "Bill",
    #                  "CTSdemoProst",
    #                  "FFPabdo",
    #                  "FusionProstate",
    #                  "Liver",
    #                  "MRIAdaptFFP",
    #                  "MRIAdaptFFS",
    #                  "MRIAdaptHFP",
    #                  "MRIAdaptHFS",
    #                  "4DCIRS1",
    #                  "PatientLiver",
    #                  "ProtonHSmall") # Patient 和 dicom的重名

    for p in patient_names:
        for pd in duplicated_PD:
            if p == pd:
                break
        else:
            unique_patient.append(p)

    for d in dicom_names:
        for pd in duplicated_PD:
            if d == pd:
                break
        else:
            unique_dicom.append(d)


def txt_PD_Export(sss):
    xlsx_listP = []
    xlsx_listD = []
    case_40_list = []
    for line in txt_path_list:  # 每一行都是一个TC的绝对地址
        address = line.rstrip('\n')  # 去掉每行末尾的换行符'\n'
        TS_name = address.split('\\')[-1].rstrip('.txt')  # 得到TC的名字

        f = open(address, encoding='utf-8')  # 打开地址下的TC errors='ignore'
        content = f.readlines()
        # print(content)

        for i in range(len(content)):
            if re.search(r'\bTest Cases\b', content[i], re.IGNORECASE):
                # print(content[i])  # i是 "*** Test Cases ***" 所在的行数
                # print(content[i: (i + 30)])
                aa = content[(i - 20): (i + 20)]
                aa.insert(0, TS_name)  # 把case名字插入到第一个
                case_40_list.append(aa)

    # print(case_40_list)
    # print(len(case_40_list)) #aaa里是每个case从 "*** Test Cases ***" 开始往下取30行的列表组成的列表嵌套

    if sss == 'patient':
        for case_40 in case_40_list:  # 每个case的40行
            str_40 = str(case_40)
            # 搜索重名的patient和dicom
            for PD in duplicated_PD:
                if re.search(r'\b%s\b' % PD, str_40, re.IGNORECASE) and \
                        re.search(r'\bLoad patient\b', str_40, re.IGNORECASE):
                    np = [case_40[0], PD]
                    if np not in xlsx_listP:
                        xlsx_listP.append(np)
            # 搜索patient
            for p in unique_patient:
                if re.search(r'\b%s\b' % p, str_40, re.IGNORECASE) and \
                        re.search(r'\bLoad patient\b', str_40, re.IGNORECASE):
                    np = [case_40[0], p]
                    if np not in xlsx_listP:
                        xlsx_listP.append(np)

        xlsx_listP = sorted(xlsx_listP, key=lambda x: x[0], reverse=False)
        wb = Workbook()
        ws = wb.active  # 对第一张sheet进行操作
        ws["A1"] = "TS-names"
        ws["B1"] = "Patient"
        for row in range(len(xlsx_listP)):
            ws.append(xlsx_listP[row])
        wb.save(r"Test_Data.xlsx")

    elif sss == 'dicom':
        for case_40 in case_40_list:  # 每个case的40行
            str_40 = str(case_40)
            # 搜索重名的patient和dicom
            for PD in duplicated_PD:
                if re.search(r'\b%s\b' % PD, str_40, re.IGNORECASE) and \
                        re.search(r'\bLoad dicom\b', str_40, re.IGNORECASE):
                    np = [case_40[0], PD]
                    if np not in xlsx_listD:
                        xlsx_listD.append(np)
            # 搜索dicom
            for d in unique_dicom:
                if re.search(r'\b%s\b' % d, str_40, re.IGNORECASE) and \
                        re.search(r'\bLoad dicom\b', str_40, re.IGNORECASE):
                    np = [case_40[0], d]
                    if np not in xlsx_listD:
                        xlsx_listD.append(np)
        xlsx_listD = sorted(xlsx_listD, key=lambda x: x[0], reverse=False)
        wb = Workbook()
        ws = wb.active  # 对第一张sheet进行操作
        ws["A1"] = "TS-names"
        ws["B1"] = "Dicom"
        for row in range(len(xlsx_listD)):
            ws.append(xlsx_listD[row])
        wb.save(r"Test_Data.xlsx")


def cs_PD_Export(xxx):
    xlsx_listP = []
    xlsx_listD = []

    if xxx == 'patient':
        for line in cs_path_list:  # 每一行都是一个TC的绝对地址
            address = line.rstrip('\n')  # 去掉每行末尾的换行符'\n'
            TS_name = address.split('\\')[-1].rstrip('.cs').rstrip('.json').rstrip('.xml')  # 得到TC的名字
            f = open(address, encoding='utf-8')  # 打开地址下的TC errors='ignore'
            content = f.readlines()
            for aline in content:  # case里其中一行
                # 搜索patient
                for p in patient_names:
                    if re.search(r'\b%s\b' % p, aline, re.IGNORECASE):
                        np = [TS_name, p]
                        if np not in xlsx_listP:
                            xlsx_listP.append(np)
        xlsx_listP = sorted(xlsx_listP, key=lambda x: x[0], reverse=False)

        wb = Workbook()
        ws = wb.active  # 对第一张sheet进行操作
        ws["A1"] = "TS-names"
        ws["B1"] = "Patient"
        for row in range(len(xlsx_listP)):
            ws.append(xlsx_listP[row])
        wb.save(r"Test_Data.xlsx")

    elif xxx == 'dicom':
        for line in cs_path_list:  # 每一行都是一个TC的绝对地址
            address = line.rstrip('\n')  # 去掉每行末尾的换行符'\n'
            TS_name = address.split('\\')[-1].rstrip('.cs').rstrip('.json').rstrip('.xml')  # 得到TC的名字
            f = open(address, encoding='utf-8')  # 打开地址下的TC errors='ignore'
            content = f.readlines()
            for aline in content:  # case里其中一行
                # 搜索dicom
                for d in dicom_names:
                    if re.search(r'\b%s\b' % d, aline, re.IGNORECASE):
                        np = [TS_name, d]
                        if np not in xlsx_listD:
                            xlsx_listD.append(np)
        xlsx_listD = sorted(xlsx_listD, key=lambda x: x[0], reverse=False)
        wb = Workbook()
        ws = wb.active  # 对第一张sheet进行操作
        ws["A1"] = "TS-names"
        ws["B1"] = "Dicom"
        for row in range(len(xlsx_listD)):
            ws.append(xlsx_listD[row])
        wb.save(r"Test_Data.xlsx")


if __name__ == '__main__':
    dir_path = r'C:\Users\yyinc04366\OneDrive - Elekta\Desktop\test data summary tool\Test'  # 文件夹目录

    txt_path_list = []
    cs_path_list = []
    find_all_case(dir_path)

    patient_names = ("4DLung",
                     "30x30x30",
                     "0505new",
                     "0505new2",
                     "002441",
                     "002443",
                     "002443TRN",
                     "002445",
                     "002445TRN",
                     "123456AA",
                     "141414",
                     "306941",
                     "0009999012",
                     "0010010777",
                     "0010117535",
                     "20140130",
                     "20160783",
                     "20190814B",
                     "111222333",
                     "111222333_NoContours",
                     "333222111",
                     "666555444",
                     "999888777",
                     "AAMDRSS2016PS",
                     "AdaptCBCT",
                     "AdaptCBCT2",
                     "AdaptCTDemo",
                     "ADTProstate",
                     "ANON76497",
                     "ArcCheck",
                     "ATP13",
                     "AutoCP",
                     "AutoMargin51102",
                     "BigAlFFS",
                     "BigAlHFS",
                     "BigPhantom",
                     "Bill",
                     "BOLUS11",
                     "Brain5TargetsTRN",
                     "breast1",
                     "breast1IMRT",
                     "BreastTRN",
                     "c1htth",
                     "CarbonLung",
                     "cem0tgdznno",
                     "CHESTnonPHANTOM",
                     "closedCentralL",
                     "cn1xt",
                     "CNNS1",
                     "cPatient",
                     "cPatient.AlgTest",
                     "cPatientProton",
                     "CrossPhantom",
                     "CT1",
                     "ctMRdosePhan",
                     "CTMRX30",
                     "CTMRXM20Y30Z50",
                     "CTMRYM40",
                     "CTMRZM50",
                     "CTSdemoHN",
                     "CTSdemoProst",
                     "CTSlung1",
                     "CTSprostate1",
                     "CTwithCTandPET",
                     "CUBE120kV",
                     "cwkjc5m51",
                     "cxrrbvw3",
                     "DemoPatient11",
                     "DepthSSDtest",
                     "DEVIL",
                     "DVHPatient1",
                     "DVHStats",
                     "DynMinLeafGap",
                     "EKK999999",
                     "ePHANTOM",
                     "FFP0CHEST",
                     "FFP88811X",
                     "FFPabdo",
                     "FFPDCMORIGIN",
                     "FFPEDFeetToHea",
                     "FFPEDHeadToFee",
                     "FFS15",
                     "FFS88811X",
                     "FFSDCMORIGIN",
                     "FFSEDFeetToHea",
                     "FFSEDHeadToFee",
                     "FFSPELVIS",
                     "ForceEDpat",
                     "ForceFillHN",
                     "FrozenDose4",
                     "FrozenTest",
                     "FrozenTest2",
                     "FrozenTest3",
                     "FrozenTestProton",
                     "FusionProstate",
                     "HalBreastXiO",
                     "HeadNeck_air",
                     "HeadProne",
                     "HFP00HEAD",
                     "HFP0CHEST",
                     "HFP88811X",
                     "HFPDCMORIGIN",
                     "HFPEDFeetToHea",
                     "HFPEDHeadToFee",
                     "HFPPELVIS",
                     "HFS00HEAD",
                     "HFS0CHEST",
                     "HFS30",
                     "HFS88811X",
                     "HFSDCMORIGIN",
                     "HFSEDFeetToHea",
                     "HFSEDHeadToFee",
                     "HFSPELVIS",
                     "HN",
                     "HN1",
                     "HNBig",
                     "HNnonPHANTOM",
                     "HNrtogIMRT",
                     "IMPTcase1",
                     "inhomtest",
                     "InvliChecksum",
                     "ionPINRTFP",
                     "ionPINRTFS",
                     "ionPINRTHP",
                     "ionPINRTHS",
                     "JamesCookMonac",
                     "K5dQtHx29P",
                     "larnumslices",
                     "Liver",
                     "LLungSBRT",
                     "LucyPhantom",
                     "Lung_air",
                     "lung_air_1",
                     "M511SSR",
                     "Matrixx",
                     "me010666x",
                     "monCOUCH",
                     "monDRPProstate",
                     "monDVHProstate",
                     "MonFP15B",
                     "monFP20B",
                     "monFP25B",
                     "monFusionProst",
                     "monFusionProstSAVE",
                     "monHN",
                     "monHPQC3121",
                     "monIMRTslabPhantm",
                     "monLung",
                     "monMLCBrain",
                     "monMLCProstate",
                     "monOROPHARYNX",
                     "monPhantom",
                     "monPlans",
                     "monPROSTATE",
                     "monPROSTATEexport",
                     "monPROSTATEmulti",
                     "monPROSTATEOLD",
                     "monPROSTATEproton",
                     "monSpherePhan",
                     "MRcntrSCO",
                     "MRIAdaptFFP",
                     "MRIAdaptFFS",
                     "MRIAdaptHFP",
                     "MRIAdaptHFS",
                     "MRIAdaptOrient",
                     "MRIDemo",
                     "MRITriangles",
                     "MRLCouch",
                     "MRX1Y1Z1",
                     "MRX20YM30Z40",
                     "MRX60",
                     "MRXM65Y55Z60",
                     "MRY50",
                     "MRZM60",
                     "MultipleStructures",
                     "nonphilips",
                     "OcuPro",
                     "OROPHARYNX",
                     "P20200925",
                     "PATIMG01",
                     "PHANTOM",
                     "PhShiftFFP50",
                     "PhShiftFFS50",
                     "PhShiftHFP50",
                     "PhShiftHFS50",
                     "PlanQuality",
                     "PointReg",
                     "PRETTYPROTONS",
                     "PROFFS18",
                     "PROHFP15",
                     "PROHFS13",
                     "prostate",
                     "Prostate_air",
                     "Prostate_norm",
                     "ProstateNodes",
                     "ProstShiftSAM",
                     "R95689791",
                     "referencePhant",
                     "RFC33982",
                     "RFC34976",
                     "RFC35090",
                     "roll",
                     "ROQS25",
                     "SBRTLung",
                     "SBRTSpine",
                     "SFUD_2",
                     "SFUD_3",
                     "SFUD1",
                     "smokePATIENT",
                     "smokePATIENT2",
                     "SPCIMGTEST",
                     "SpotLevel",
                     "SPTOriginalEUR",
                     "SSDTest2",
                     "Test1Proton",
                     "Test2Proton",
                     "Test9Proton",
                     "ThoracicCTPET",
                     "TolBreast",
                     "TPPC17A03PH",
                     "TwoBolus",
                     "UnityPatient1",
                     "UPMCLIV2",
                     "UPMCPANC1",
                     "UserAuth",
                     "VarianVMAT",
                     "wccccm",
                     "WeightLoss",
                     "XiOLung",
                     "EHU1412",
                     "4DCIRS1",
                     "111111",
                     "0000463294.anonymized",
                     "0000492064.anonymized",
                     "42482527",
                     "42482527_PerformanceTest",
                     "77378376",
                     "A4DCIRS1",
                     "cPatientCTRS_NonSquare",
                     "DUCKDAISY",
                     "HeadNeck_air_PerformanceTest",
                     "HP6834",
                     "Liver-4537",
                     "LockedLiver",
                     "lung_air_PerfomanceTest",
                     "MRIDemo177",
                     "MRIDemoCP",
                     "PatientLiver",
                     "ProtonCase",
                     "ProtonHBig",
                     "ProtonHSmall",
                     "ProtonPlanReview",
                     "ROQS25",
                     "smokePATIENT",
                     "smokePATIENT2",
                     "Test1",
                     "Test1IDD",
                     "Test3",
                     "Test3Air",
                     "Test4",
                     "Test4Water",
                     "Test6",
                     "Test8IDD",
                     "Test10",
                     "Test11RBE")  # 完整的patient list
    dicom_names = ("1ATLABDO_FFPMR_Day1",
                   "1ATLABDO_FFPMR_Day2",
                   "1ATLABDO_FFSMR_Day1",
                   "1ATLABDO_FFSMR_Day2",
                   "1ATLABDO_HFPMR_Day1",
                   "1ATLABDO_HFPMR_Day2",
                   "1ATLABDO_HFSMR_Day1",
                   "1ATLABDO_HFSMR_Day2",
                   "3D",
                   "3DSTACarc",
                   "4DCIRS1",
                   "4DLung",
                   "4011",
                   "393456",
                   "17112006",
                   "6012247133",
                   "AddonMLC",
                   "Applicator",
                   "BigAlFFS",
                   "BigAlHFS",
                   "Bill",
                   "BlackPixels",
                   "Block",
                   "BO2",
                   "BolusImportLiver",
                   "BolusOncentra2",
                   "BREAST0719",
                   "BUG_6255_PhantomPlan",
                   "Carbon_FFP",
                   "Carbon_FFP_T_PTS",
                   "Carbon_FFS",
                   "Carbon_FFS_T_PTS",
                   "Carbon_HFP",
                   "Carbon_HFP_T_PTS",
                   "Carbon_HFS",
                   "Carbon_HFS_T_PTS",
                   "ch2o1xr2rmFFP",
                   "ch2o1xr2rmFFS",
                   "ch2o1xr2rmHFP",
                   "ch2o1xr2rmHFS",
                   "Chordoma_2",
                   "ConformalRT",
                   "cPatientNonSquarePixelMR",
                   "CS_CT_iBEAM_CouchTop",
                   "CS_CT_MULTISERIES",
                   "CS_CTMR_PICKER",
                   "CS_MR_TILT",
                   "CS_MRI_NON_SQR_PX",
                   "CS_NEARLYAXIALMR",
                   "CS_NOMERG_SIEMENS",
                   "CS_PET_BLACK_HOLES",
                   "CS_PET_GESLICE",
                   "CS_PET_GEVOLUME",
                   "CS_PETCT_GEDISC_JUN2002",
                   "CS_RTD_ECLIPSE",
                   "CS_RTD_ECLIPSE_IMPORT",
                   "CS_RTD_KONRAD",
                   "CS_RTD_ONCENTRAsep2005",
                   "CS_RTD_TOMOHN",
                   "CS_RTD_XIOIMRTARC",
                   "CS_RTD_XIORTPLINK",
                   "CS_RTP_ACQSIM_APRIL2005",
                   "CS_RTP_ADVSIM_JUL2005",
                   "CS_RTP_ONCENTRA_JUL2005",
                   "CS_RTP_THERAPLAN",
                   "CS_RTP_XIO_FORSSIMPORT",
                   "CS_RTS_ACQSIM_NASO",
                   "CS_RTS_COHERENCE",
                   "CT_RTS_COHERENCE",
                   "CT_UnEven",
                   "CT_VF",
                   "CTMR",
                   "CTOR03",
                   "CTPETSiemens",
                   "CTSdemoProst",
                   "DCAT_CDR_Bug_Data",
                   "Demo_Phantom_1",
                   "DemoPatient10",
                   "dMLC",
                   "DRPDepthTest",
                   "DuplicateInstanceNumber",
                   "DuplicateSliceLocation",
                   "DuplicateSliceLocationNoInstanceNumber",
                   "DynConformalArc",
                   "ED_TestPhantoms",
                   "EnergyError",
                   "ErrorThrowout",
                   "FEET1st^SUPINE_ABC-DEFGHIJKLMNOPQRSTUVWXYZ.abcdefghijklmnopqrstu",
                   "FFP_PhantomSkull",
                   "FFPabdo",
                   "FFS",
                   "FFS_RealPatient",
                   "FFS_roll-15",
                   "Fieldsplit",
                   "FusionProstate",
                   "GE_AdvSim_2field_BreastPlan",
                   "GEPatient",
                   "GESIM",
                   "Grid9",
                   "HeadSupine",
                   "HFP",
                   "HFP_1024Images",
                   "HFP_roll-15",
                   "HFS_RealPatientRTSS",
                   "HFS_roll-15",
                   "InvalidSnout",
                   "InvalidSP",
                   "ionRSThicknessError",
                   "IOPnoTranswithoutMacro",
                   "IOPxMACRO",
                   "Liver",
                   "mARC",
                   "MMRO17A02EL_REG_Nucletron",
                   "MMRO17A06EL_REG_Varian",
                   "MMRO17A06RA_REG",
                   "MMRO17A06RA_REG_RaySearch",
                   "MMRO17A10VA_REG_3SET",
                   "MMRO19A03EL",
                   "Mon4TESTING01",
                   "MONACODVH",
                   "MonIonDicom",
                   "monPhan",
                   "MR",
                   "MR_OBLIQUE_DATA",
                   "MR_PLANE_CUTS",
                   "MRIAdaptFFP",
                   "MRIAdaptFFS",
                   "MRIAdaptHFP",
                   "MRIAdaptHFP_IPP",
                   "MRIAdaptHFS",
                   "MRIAdaptHFS_IPP",
                   "MRMultiPlan",
                   "MRPuppetOrient",
                   "MRTestDemo",
                   "MRTestPatientHN",
                   "MultiDelivery",
                   "MultiDuplicateSliceLocation",
                   "MultiFrac",
                   "NomappingTU",
                   "Oncentra3",
                   "OrientationTestPatient1",
                   "p5MUeeYS0w",
                   "PatientLiver",
                   "Ph.Orig.FFP",
                   "Ph.Orig.FFS",
                   "Ph.Orig.HFP",
                   "Ph.Orig.HFS",
                   "Ph.PrismFadeZ",
                   "Ph.Shift.FFP",
                   "Ph.Shift.FFS",
                   "Ph.Shift.HFP",
                   "Ph.Shift.HFS",
                   "Ph.Shift.HFS_Simplify",
                   "Phantom_NullStudy",
                   "PhDosePrism10",
                   "PhilipsPatient",
                   "PhillipsPetCT",
                   "ProneData",
                   "prostate-umb1-CBCT",
                   "prostate-umb1-MRI",
                   "ProstShift_DICOM",
                   "ProtonHSmall",
                   "Regression_5.5",
                   "RFC27418Dcm",
                   "RolledCT",
                   "RSIDerror",
                   "SE000001anon",
                   "secondarymonPROSTATE",
                   "secondaryMRIDemo",
                   "Segerror",
                   "SetupBeam",
                   "SFUD4_ClinicalCase",
                   "SiemensPatient",
                   "SnoutIDError",
                   "SpecExprt",
                   "SpecImg",
                   "SPHERE120kV",
                   "SSDtest",
                   "SSDtest2",
                   "stepnshoot",
                   "SwedishDicom",
                   "T1Prostate",
                   "TestProstatePatient",
                   "TOSHIBA_IMG",
                   "TPPC17A03BR_REG_MIM",
                   "TPPC17A04BR_REG_Brainlab",
                   "TuneIDerror",
                   "Unity01",
                   "vmat",
                   "vmatnew",
                   "VSADtest",
                   "Wedge",
                   "WinLevelPET",
                   "YawPitchRollCT",
                   "ZeroSliceThickness",
                   "ZZZ_CT_1.25mmThinkness",
                   "4DCIRS1SRO",
                   "4DElektaXVi",
                   "4DElektaXviNoStudy",
                   "4DGE1",
                   "4DGE2",
                   "4DGE4",
                   "4DGE5",
                   "4DGE6",
                   "4DManyStudies",
                   "4DPhilips1",
                   "4DPhilips2",
                   "4DPhilips3",
                   "4DPhilips4",
                   "4DPhilips5",
                   "4DPhilips6",
                   "4DPhilips7",
                   "4DPhilips8",
                   "4DSiemens1",
                   "4DSiemens2",
                   "4DSiemens3",
                   "4DSiemens4",
                   "4DSiemens5",
                   "4DSiemens6",
                   "4DToshiba4",
                   "000006+1485",
                   "000006+1541",
                   "000006+1648",
                   "0000061485",
                   "CarpePTS",
                   "crjcr1q",
                   "CTdisney",
                   "ctMRdosePhan_MRI",
                   "ctMRdosePhanMRsurvey",
                   "DataBug15",
                   "DosePhantom",
                   "DosePhantoms",
                   "DuplicateSliceLocation4D",
                   "ExcCase1",
                   "I18Neiou",
                   "IPPShift",
                   "Multiple_Size_Image",
                   "PET_Phantom",
                   "PETSUVA",
                   "PETSUVB",
                   "phantom",
                   "SamplePatientsForImport",
                   "testSUV",
                   "WINLEVEL_PRESET_3",
                   "WINLEVEL_PRESET_4")
    # print(len(txt_path_list))  # 1936
    # print(len(cs_path_list))  # 218

    # CT1, prostate, Liver, HN, Test1, Test3
    # patient_names = ("4DLung",
    #                  "30x30x30",
    #                  "0505new",
    #                  "0505new2",
    #                  "002441",
    #                  "002443",
    #                  "002443TRN",
    #                  "002445",
    #                  "002445TRN",
    #                  "123456AA",
    #                  "141414",
    #                  "306941",
    #                  "0009999012",
    #                  "0010010777",
    #                  "0010117535",
    #                  "20140130",
    #                  "20160783",
    #                  "20190814B",
    #                  "111222333",
    #                  "111222333_NoContours",
    #                  "333222111",
    #                  "666555444",
    #                  "999888777",
    #                  "AAMDRSS2016PS",
    #                  "AdaptCBCT",
    #                  "AdaptCBCT2",
    #                  "AdaptCTDemo",
    #                  "ADTProstate",
    #                  "ANON76497",
    #                  "ArcCheck",
    #                  "ATP13",
    #                  "AutoCP",
    #                  "AutoMargin51102",
    #                  "BigAlFFS",
    #                  "BigAlHFS",
    #                  "BigPhantom",
    #                  "Bill",
    #                  "BOLUS11",
    #                  "Brain5TargetsTRN",
    #                  "breast1",
    #                  "breast1IMRT",
    #                  "BreastTRN",
    #                  "c1htth",
    #                  "CarbonLung",
    #                  "cem0tgdznno",
    #                  "CHESTnonPHANTOM",
    #                  "closedCentralL",
    #                  "cn1xt",
    #                  "CNNS1",
    #                  "cPatient",
    #                  "cPatient.AlgTest",
    #                  "cPatientProton",
    #                  "CrossPhantom",
    #                  # "CT1",
    #                  "ctMRdosePhan",
    #                  "CTMRX30",
    #                  "CTMRXM20Y30Z50",
    #                  "CTMRYM40",
    #                  "CTMRZM50",
    #                  "CTSdemoHN",
    #                  "CTSdemoProst",
    #                  "CTSlung1",
    #                  "CTSprostate1",
    #                  "CTwithCTandPET",
    #                  "CUBE120kV",
    #                  "cwkjc5m51",
    #                  "cxrrbvw3",
    #                  "DemoPatient11",
    #                  "DepthSSDtest",
    #                  "DEVIL",
    #                  "DVHPatient1",
    #                  "DVHStats",
    #                  "DynMinLeafGap",
    #                  "EKK999999",
    #                  "ePHANTOM",
    #                  "FFP0CHEST",
    #                  "FFP88811X",
    #                  "FFPabdo",
    #                  "FFPDCMORIGIN",
    #                  "FFPEDFeetToHea",
    #                  "FFPEDHeadToFee",
    #                  "FFS15",
    #                  "FFS88811X",
    #                  "FFSDCMORIGIN",
    #                  "FFSEDFeetToHea",
    #                  "FFSEDHeadToFee",
    #                  "FFSPELVIS",
    #                  "ForceEDpat",
    #                  "ForceFillHN",
    #                  "FrozenDose4",
    #                  "FrozenTest",
    #                  "FrozenTest2",
    #                  "FrozenTest3",
    #                  "FrozenTestProton",
    #                  "FusionProstate",
    #                  "HalBreastXiO",
    #                  "HeadNeck_air",
    #                  "HeadProne",
    #                  "HFP00HEAD",
    #                  "HFP0CHEST",
    #                  "HFP88811X",
    #                  "HFPDCMORIGIN",
    #                  "HFPEDFeetToHea",
    #                  "HFPEDHeadToFee",
    #                  "HFPPELVIS",
    #                  "HFS00HEAD",
    #                  "HFS0CHEST",
    #                  "HFS30",
    #                  "HFS88811X",
    #                  "HFSDCMORIGIN",
    #                  "HFSEDFeetToHea",
    #                  "HFSEDHeadToFee",
    #                  "HFSPELVIS",
    #                  # "HN",
    #                  "HN1",
    #                  "HNBig",
    #                  "HNnonPHANTOM",
    #                  "HNrtogIMRT",
    #                  "IMPTcase1",
    #                  "inhomtest",
    #                  "InvliChecksum",
    #                  "ionPINRTFP",
    #                  "ionPINRTFS",
    #                  "ionPINRTHP",
    #                  "ionPINRTHS",
    #                  "JamesCookMonac",
    #                  "K5dQtHx29P",
    #                  "larnumslices",
    #                  # "Liver",
    #                  "LLungSBRT",
    #                  "LucyPhantom",
    #                  "Lung_air",
    #                  "lung_air_1",
    #                  "M511SSR",
    #                  "Matrixx",
    #                  "me010666x",
    #                  "monCOUCH",
    #                  "monDRPProstate",
    #                  "monDVHProstate",
    #                  "MonFP15B",
    #                  "monFP20B",
    #                  "monFP25B",
    #                  "monFusionProst",
    #                  "monFusionProstSAVE",
    #                  "monHN",
    #                  "monHPQC3121",
    #                  "monIMRTslabPhantm",
    #                  "monLung",
    #                  "monMLCBrain",
    #                  "monMLCProstate",
    #                  "monOROPHARYNX",
    #                  "monPhantom",
    #                  "monPlans",
    #                  "monPROSTATE",
    #                  "monPROSTATEexport",
    #                  "monPROSTATEmulti",
    #                  "monPROSTATEOLD",
    #                  "monPROSTATEproton",
    #                  "monSpherePhan",
    #                  "MRcntrSCO",
    #                  "MRIAdaptFFP",
    #                  "MRIAdaptFFS",
    #                  "MRIAdaptHFP",
    #                  "MRIAdaptHFS",
    #                  "MRIAdaptOrient",
    #                  "MRIDemo",
    #                  "MRITriangles",
    #                  "MRLCouch",
    #                  "MRX1Y1Z1",
    #                  "MRX20YM30Z40",
    #                  "MRX60",
    #                  "MRXM65Y55Z60",
    #                  "MRY50",
    #                  "MRZM60",
    #                  "MultipleStructures",
    #                  "nonphilips",
    #                  "OcuPro",
    #                  "OROPHARYNX",
    #                  "P20200925",
    #                  "PATIMG01",
    #                  "PHANTOM",
    #                  "PhShiftFFP50",
    #                  "PhShiftFFS50",
    #                  "PhShiftHFP50",
    #                  "PhShiftHFS50",
    #                  "PlanQuality",
    #                  "PointReg",
    #                  "PRETTYPROTONS",
    #                  "PROFFS18",
    #                  "PROHFP15",
    #                  "PROHFS13",
    #                  # "prostate",
    #                  "Prostate_air",
    #                  "Prostate_norm",
    #                  "ProstateNodes",
    #                  "ProstShiftSAM",
    #                  "R95689791",
    #                  "referencePhant",
    #                  "RFC33982",
    #                  "RFC34976",
    #                  "RFC35090",
    #                  "roll",
    #                  "ROQS25",
    #                  "SBRTLung",
    #                  "SBRTSpine",
    #                  "SFUD_2",
    #                  "SFUD_3",
    #                  "SFUD1",
    #                  "smokePATIENT",
    #                  "smokePATIENT2",
    #                  "SPCIMGTEST",
    #                  "SpotLevel",
    #                  "SPTOriginalEUR",
    #                  "SSDTest2",
    #                  "Test1Proton",
    #                  "Test2Proton",
    #                  "Test9Proton",
    #                  "ThoracicCTPET",
    #                  "TolBreast",
    #                  "TPPC17A03PH",
    #                  "TwoBolus",
    #                  "UnityPatient1",
    #                  "UPMCLIV2",
    #                  "UPMCPANC1",
    #                  "UserAuth",
    #                  "VarianVMAT",
    #                  "wccccm",
    #                  "WeightLoss",
    #                  "XiOLung",
    #                  "EHU1412",
    #                  "4DCIRS1",
    #                  "111111",
    #                  "0000463294.anonymized",
    #                  "0000492064.anonymized",
    #                  "42482527",
    #                  "42482527_PerformanceTest",
    #                  "77378376",
    #                  "A4DCIRS1",
    #                  "cPatientCTRS_NonSquare",
    #                  "DUCKDAISY",
    #                  "HeadNeck_air_PerformanceTest",
    #                  "HP6834",
    #                  "Liver-4537",
    #                  "LockedLiver",
    #                  "lung_air_PerfomanceTest",
    #                  "MRIDemo177",
    #                  "MRIDemoCP",
    #                  "PatientLiver",
    #                  "ProtonCase",
    #                  "ProtonHBig",
    #                  "ProtonHSmall",
    #                  "ProtonPlanReview",
    #                  "ROQS25",
    #                  "smokePATIENT",
    #                  "smokePATIENT2",
    #                  # "Test1",
    #                  "Test1IDD",
    #                  # "Test3",
    #                  "Test3Air",
    #                  "Test4",
    #                  "Test4Water",
    #                  "Test6",
    #                  "Test8IDD",
    #                  "Test10",
    #                  "Test11RBE")
    #
    # # 3D, wedge, dMLC, CTSdemoProst, MR, vmat, Liver, ProtonHSmall,
    # # Applicator, Block, BigAlFFS, BigAlHFS, HFP, FFS, Bill, SetupBeam, phantom
    # dicom_names = ("1ATLABDO_FFPMR_Day1",
    #                "1ATLABDO_FFPMR_Day2",
    #                "1ATLABDO_FFSMR_Day1",
    #                "1ATLABDO_FFSMR_Day2",
    #                "1ATLABDO_HFPMR_Day1",
    #                "1ATLABDO_HFPMR_Day2",
    #                "1ATLABDO_HFSMR_Day1",
    #                "1ATLABDO_HFSMR_Day2",
    #                # "3D",
    #                "3DSTACarc",
    #                "4DCIRS1",
    #                "4DLung",
    #                "4011",
    #                "393456",
    #                "17112006",
    #                "6012247133",
    #                "AddonMLC",
    #                # "Applicator",
    #                # "BigAlFFS",
    #                # "BigAlHFS",
    #                # "Bill",
    #                "BlackPixels",
    #                # "Block",
    #                "BO2",
    #                "BolusImportLiver",
    #                "BolusOncentra2",
    #                "BREAST0719",
    #                "BUG_6255_PhantomPlan",
    #                "Carbon_FFP",
    #                "Carbon_FFP_T_PTS",
    #                "Carbon_FFS",
    #                "Carbon_FFS_T_PTS",
    #                "Carbon_HFP",
    #                "Carbon_HFP_T_PTS",
    #                "Carbon_HFS",
    #                "Carbon_HFS_T_PTS",
    #                "ch2o1xr2rmFFP",
    #                "ch2o1xr2rmFFS",
    #                "ch2o1xr2rmHFP",
    #                "ch2o1xr2rmHFS",
    #                "Chordoma_2",
    #                "ConformalRT",
    #                "cPatientNonSquarePixelMR",
    #                "CS_CT_iBEAM_CouchTop",
    #                "CS_CT_MULTISERIES",
    #                "CS_CTMR_PICKER",
    #                "CS_MR_TILT",
    #                "CS_MRI_NON_SQR_PX",
    #                "CS_NEARLYAXIALMR",
    #                "CS_NOMERG_SIEMENS",
    #                "CS_PET_BLACK_HOLES",
    #                "CS_PET_GESLICE",
    #                "CS_PET_GEVOLUME",
    #                "CS_PETCT_GEDISC_JUN2002",
    #                "CS_RTD_ECLIPSE",
    #                "CS_RTD_ECLIPSE_IMPORT",
    #                "CS_RTD_KONRAD",
    #                "CS_RTD_ONCENTRAsep2005",
    #                "CS_RTD_TOMOHN",
    #                "CS_RTD_XIOIMRTARC",
    #                "CS_RTD_XIORTPLINK",
    #                "CS_RTP_ACQSIM_APRIL2005",
    #                "CS_RTP_ADVSIM_JUL2005",
    #                "CS_RTP_ONCENTRA_JUL2005",
    #                "CS_RTP_THERAPLAN",
    #                "CS_RTP_XIO_FORSSIMPORT",
    #                "CS_RTS_ACQSIM_NASO",
    #                "CS_RTS_COHERENCE",
    #                "CT_RTS_COHERENCE",
    #                "CT_UnEven",
    #                "CT_VF",
    #                "CTMR",
    #                "CTOR03",
    #                "CTPETSiemens",
    #                # "CTSdemoProst",
    #                "DCAT_CDR_Bug_Data",
    #                "Demo_Phantom_1",
    #                "DemoPatient10",
    #                # "dMLC",
    #                "DRPDepthTest",
    #                "DuplicateInstanceNumber",
    #                "DuplicateSliceLocation",
    #                "DuplicateSliceLocationNoInstanceNumber",
    #                "DynConformalArc",
    #                "ED_TestPhantoms",
    #                "EnergyError",
    #                "ErrorThrowout",
    #                "FEET1st^SUPINE_ABC-DEFGHIJKLMNOPQRSTUVWXYZ.abcdefghijklmnopqrstu",
    #                "FFP_PhantomSkull",
    #                "FFPabdo",
    #                # "FFS",
    #                "FFS_RealPatient",
    #                "FFS_roll-15",
    #                "Fieldsplit",
    #                "FusionProstate",
    #                "GE_AdvSim_2field_BreastPlan",
    #                "GEPatient",
    #                "GESIM",
    #                "Grid9",
    #                "HeadSupine",
    #                # "HFP",
    #                "HFP_1024Images",
    #                "HFP_roll-15",
    #                "HFS_RealPatientRTSS",
    #                "HFS_roll-15",
    #                "InvalidSnout",
    #                "InvalidSP",
    #                "ionRSThicknessError",
    #                "IOPnoTranswithoutMacro",
    #                "IOPxMACRO",
    #                # "Liver",
    #                "mARC",
    #                "MMRO17A02EL_REG_Nucletron",
    #                "MMRO17A06EL_REG_Varian",
    #                "MMRO17A06RA_REG",
    #                "MMRO17A06RA_REG_RaySearch",
    #                "MMRO17A10VA_REG_3SET",
    #                "MMRO19A03EL",
    #                "Mon4TESTING01",
    #                "MONACODVH",
    #                "MonIonDicom",
    #                "monPhan",
    #                # "MR",
    #                "MR_OBLIQUE_DATA",
    #                "MR_PLANE_CUTS",
    #                "MRIAdaptFFP",
    #                "MRIAdaptFFS",
    #                "MRIAdaptHFP",
    #                "MRIAdaptHFP_IPP",
    #                "MRIAdaptHFS",
    #                "MRIAdaptHFS_IPP",
    #                "MRMultiPlan",
    #                "MRPuppetOrient",
    #                "MRTestDemo",
    #                "MRTestPatientHN",
    #                "MultiDelivery",
    #                "MultiDuplicateSliceLocation",
    #                "MultiFrac",
    #                "NomappingTU",
    #                "Oncentra3",
    #                "OrientationTestPatient1",
    #                "p5MUeeYS0w",
    #                "PatientLiver",
    #                "Ph.Orig.FFP",
    #                "Ph.Orig.FFS",
    #                "Ph.Orig.HFP",
    #                "Ph.Orig.HFS",
    #                "Ph.PrismFadeZ",
    #                "Ph.Shift.FFP",
    #                "Ph.Shift.FFS",
    #                "Ph.Shift.HFP",
    #                "Ph.Shift.HFS",
    #                "Ph.Shift.HFS_Simplify",
    #                "Phantom_NullStudy",
    #                "PhDosePrism10",
    #                "PhilipsPatient",
    #                "PhillipsPetCT",
    #                "ProneData",
    #                "prostate-umb1-CBCT",
    #                "prostate-umb1-MRI",
    #                "ProstShift_DICOM",
    #                "ProtonHSmall",
    #                "Regression_5.5",
    #                "RFC27418Dcm",
    #                "RolledCT",
    #                "RSIDerror",
    #                "SE000001anon",
    #                "secondarymonPROSTATE",
    #                "secondaryMRIDemo",
    #                "Segerror",
    #                # "SetupBeam",
    #                "SFUD4_ClinicalCase",
    #                "SiemensPatient",
    #                "SnoutIDError",
    #                "SpecExprt",
    #                "SpecImg",
    #                "SPHERE120kV",
    #                "SSDtest",
    #                "SSDtest2",
    #                "stepnshoot",
    #                "SwedishDicom",
    #                "T1Prostate",
    #                "TestProstatePatient",
    #                "TOSHIBA_IMG",
    #                "TPPC17A03BR_REG_MIM",
    #                "TPPC17A04BR_REG_Brainlab",
    #                "TuneIDerror",
    #                "Unity01",
    #                # "vmat",
    #                "vmatnew",
    #                "VSADtest",
    #                # "Wedge",
    #                "WinLevelPET",
    #                "YawPitchRollCT",
    #                "ZeroSliceThickness",
    #                "ZZZ_CT_1.25mmThinkness",
    #                "4DCIRS1SRO",
    #                "4DElektaXVi",
    #                "4DElektaXviNoStudy",
    #                "4DGE1",
    #                "4DGE2",
    #                "4DGE4",
    #                "4DGE5",
    #                "4DGE6",
    #                "4DManyStudies",
    #                "4DPhilips1",
    #                "4DPhilips2",
    #                "4DPhilips3",
    #                "4DPhilips4",
    #                "4DPhilips5",
    #                "4DPhilips6",
    #                "4DPhilips7",
    #                "4DPhilips8",
    #                "4DSiemens1",
    #                "4DSiemens2",
    #                "4DSiemens3",
    #                "4DSiemens4",
    #                "4DSiemens5",
    #                "4DSiemens6",
    #                "4DToshiba4",
    #                "000006+1485",
    #                "000006+1541",
    #                "000006+1648",
    #                "0000061485",
    #                "CarpePTS",
    #                "crjcr1q",
    #                "CTdisney",
    #                "ctMRdosePhan_MRI",
    #                "ctMRdosePhanMRsurvey",
    #                "DataBug15",
    #                "DosePhantom",
    #                "DosePhantoms",
    #                "DuplicateSliceLocation4D",
    #                "ExcCase1",
    #                "I18Neiou",
    #                "IPPShift",
    #                "Multiple_Size_Image",
    #                "PET_Phantom",
    #                "PETSUVA",
    #                "PETSUVB",
    #                # "phantom",
    #                "SamplePatientsForImport",
    #                "testSUV",
    #                "WINLEVEL_PRESET_3",
    #                "WINLEVEL_PRESET_4")

    duplicated_PD = []
    unique_patient = []
    unique_dicom = []
    unique_PD()
    all_patient_dicom = unique_patient + unique_dicom + duplicated_PD

    txt_PD_Export('dicom')
    cs_PD_Export('patient')

    # print(unique_patient)
    # print(len(unique_patient))
    # print(unique_dicom)
    # print(len(unique_dicom))
    # print(duplicated_PD)
    # print(len(duplicated_PD))
    # print(all_patient_dicom)
    # print(len(all_patient_dicom))

    # print(xlsx_listP)
    # print(xlsx_listD)
    #
    # print(len(xlsx_listP))
    # print(len(xlsx_listD))
    #
    # print(unique_patient)
    # print(len(unique_patient))
    #
    # print(unique_dicom)
    # print(len(unique_dicom))
    #
    # print(duplicated_PD)
    # print(len(duplicated_PD))
